### ISSUE TITLE
MySQL connection problems

### ISSUE THREAD

**Issue by jascotty2** [iConomy/Core#10]
downloaded 4.3(.3), seemed to work, so i edited the config to use my MySQL database, and got this:

"""  
2011-03-04 22:34:41 [SEVERE] null (Is it up to date?)
java.lang.NullPointerException
at com.nijiko.coelho.iConomy.iConomy.onDisable(iConomy.java:170)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:142)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:441)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:199)
at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:102)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:140)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:187)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:79)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:60)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:187)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:174)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:120)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:227)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
"""

changing it back to SQLite makes it work again.. any idea what could be causing this?

then tried 4.2.. worked fine until i tried to use MySQL

"""  
2011-03-04 22:55:03 [INFO] [iConomy] Failed to save accounts and has been disabled.
2011-03-04 22:55:03 [INFO] [iConomy] Failed to connect to database: com.mysql.jdbc.Driver
"""

i'm using the correct login info (i've logged in using the provided auth info several times).. why can it not connect?
(using Craftbukkit version git-Bukkit-0.0.0-458-g557f3d2-b440jnks (MC: 1.3) in ubuntu/debian, running mysql-server)
(using Craftbukkit version git-Bukkit-0.0.0-458-g557f3d2-b440jnks (MC: 1.3) in ubuntu/debian, running mysql-server: 5.1.49-3 (Debian) and 5.1.49-1ubuntu8.1 (Ubuntu) on my test computer)

**Comment by nijikokun** [comment]
It's working fine here, I cannot replicate.

**Comment by jascotty2** [comment]
updated to 4.4.3 and the latest bukkit recommended build, and now getting another error before the previous error:

"""  
23:59:49 [INFO] [iConomy] Configuration Integrity Start:
23:59:49 [INFO]     - System.Database.Cache is null or missing, Defaulting to: true
23:59:49 [INFO] [iConomy] Configuration Integrity End.
23:59:49 [INFO] [iConomy] Failed to connect to database: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
23:59:49 [SEVERE] null loading iConomy v4.4 (Is it up to date?)
java.lang.NullPointerException
    at com.nijiko.coelho.iConomy.iConomy.onDisable(iConomy.java:188)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:120)
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:428)
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:199)
    at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:120)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:414)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:187)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:83)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:61)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:204)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:191)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:131)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:246)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
"""

**Comment by jascotty2** [comment]
JUST FIGURED IT OUT :D

your plugin automatically downloads the SQLite dependency, but not the MySQL one.
once i downloaded & put in the lib folder, it started up fine :D

(you probably should have some error checking for that null exception, though.)
