### ISSUE TITLE
Internal Error: iConomy 5.0.1 /money

### ISSUE THREAD

**Issue by ZakuPilotHiggs** [iConomy/Core#103]
2011-06-19 03:03:31 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v5.01
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:128)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:287)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:712)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:678)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:671)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:32)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:75)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:399)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:309)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.NullPointerException
    at com.iConomy.util.Messaging.argument(Messaging.java:42)
    at com.iConomy.util.Template.parse(Template.java:119)
    at com.iConomy.entity.Players.showBalance(Players.java:451)
    at com.iConomy.entity.Players.onPlayerCommand(Players.java:1554)
    at com.iConomy.iConomy.onCommand(iConomy.java:218)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
    ... 12 more

**Comment by ZakuPilotHiggs** [comment]
Reinstalled. Works for now.
