### ISSUE TITLE
4.3 does not work with CB 493

### ISSUE THREAD

**Issue by uncovery** [iConomy/Core#11]
18:24:54 [SEVERE] null loading iConomy v4.3 (Is it up to date?)
java.lang.NullPointerException
at com.nijiko.coelho.iConomy.iConomy.onDisable(iConomy.java:170)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:120)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:428)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:199)
at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:102)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:414)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:187)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:83)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:61)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:204)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:191)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:131)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:246)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)

also:

the ( ) in the download link is not compatible with wget. Please use a different format.

**Comment by nijikokun** [comment]
It's compatible with wget, I did it earlier. surround with quotes.

This should be fixed in 4.4
