### ISSUE TITLE
Conflict with H2 database using.

### ISSUE THREAD

**Issue by IJosephI** [iConomy/Core#112]
I have 2 plugins using H2 database - iConomy & XAuth, but they have conflict of using the same library -
server_folder\lib\ 
Help me, please, to solve this problem. 

Error code:

20:58:03 [SEVERE] [xAuth] Could not connect to H2 database!
java.sql.SQLException: invalid database address: jdbc:h2:plugins\xAuth\xAuth;IGNORECASE=TRUE
    at org.sqlite.JDBC.createConnection(JDBC.java:74)
    at org.sqlite.JDBC.connect(JDBC.java:64)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at com.cypherx.xauth.datamanager.DataManager.connectH2(DataManager.java:61)
    at com.cypherx.xauth.datamanager.DataManager.<init>(DataManager.java:38)
    at com.cypherx.xauth.xAuth.onEnable(xAuth.java:65)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:857)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:264)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:151)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:136)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:358)
    at org.bukkit.command.SimpleCommandMap$ReloadCommand.execute(SimpleCommandMap.java:281)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:290)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:480)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:465)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:361)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-07-01 20:58:03 [SEVERE] [xAuth] Disabling - No connection to database
2011-07-01 20:58:03 [INFO] [xAuth] v2.0b3 Disabled!

p.s.  iconomy starts before xauth, so xauth have this error message

**Comment by bigto** [comment]
problem solved?

**Comment by IJosephI** [comment]
No, i changed my authenticate plugin to authme and started using mysql.
