### ISSUE TITLE
H2 issue

### ISSUE THREAD

**Issue by dzekins** [iConomy/Core#114]
Could not load 'plugins\h2.jar' in folder 'plugins': 
java.io.FileNotFoundException: Jar does not contain plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:64)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:199)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:118)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:89)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:132)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:335)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-07-03 17:36:46 [SEVERE] Could not load 'plugins\mysql-connector-java-bin.jar' in folder 'plugins': 
java.io.FileNotFoundException: Jar does not contain plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:64)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:199)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:118)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:89)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:132)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:335)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

they bouth are in that folder and are up to date

**Comment by nijikokun** [comment]
should be in ../lib/h2.jar
