### ISSUE TITLE
[SEVERE] null loading iConomy v4.3 (Is it up to date?)

### ISSUE THREAD

**Issue by j3lack** [iConomy/Core#14]
I have been getting this error constantly even when i update iConomy i've tried checking my configs and issues with other mods but i'm obviously missing something. I'm running Bukkit 493, Essentials, Permissions, LWC, MCMMO, iConomyChestShop and TombStone on my server and they all load fine and so does sqlite.
here is the full error message i get from iConomy...

```
2011-03-06 08:28:03 [SEVERE] null loading iConomy v4.3 (Is it up to date?)
java.lang.NullPointerException
at com.nijiko.coelho.iConomy.iConomy.onDisable(iConomy.java:170)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:120)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:428)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:199)
at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:92)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:414)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:187)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:83)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:61)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:204)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:191)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:131)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:246)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
```

and this is what it gives me when i just try the /money command in game...

```
2011-03-06 16:07:16 [SEVERE] java.lang.NullPointerException
2011-03-06 16:07:16 [SEVERE]    at com.nijiko.coelho.iConomy.iConomy.onCommand(iConomy.java:221)
2011-03-06 16:07:16 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:31)
2011-03-06 16:07:16 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:80)
2011-03-06 16:07:16 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:183)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetServerHandler.c(NetServerHandler.java:619)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:582)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:576)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.Packet3Chat.a(SourceFile:24)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetworkManager.a(SourceFile:230)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:75)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:357)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:272)
2011-03-06 16:07:16 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
```

any ideas why this is happening would be greatly appreciated cause i'm at a loss...

Note: after looking for help everywhere in the forums, i'm pretty sure my problem is that i lack a database. in the previous versions iConomy generated a flatfile, but the newer versions are designed around sql and apparently don't generate their own database but need a flatfile to modify. however i'm reinstalling iConomy from scratch so i don't have that flatfile to begin with. if this is for sure my problem i think alot of other people are having it and we could do with either a download on the bukkit forums or have iconomy generate that database for us.

**Comment by nijikokun** [comment]
They do generate SQL here: http://iconomy.nexua.org/flatfile.php

You will have to have a database installed, usually that error occurs if you are reloading with a new config, and your database cannot connect, or you are missing the library.

This is not an actual error, its more just saying that you aren't connected to a database.

Check a few lines before that for another error that will tell you more about what is happening.

**Comment by j3lack** [comment]
Ok so assuming there is a database already, where would i find it? in the lib directory with the sqlitejdbcv056.jar or is it within that jar file? Also, how would i go about making that database connect if it is not?
Note: I noticed with LWC it has created a sqlitejdbc.dll but my sqlite for iConomy has not created anything within its lib directory. 

There are no lines with errors other than the ones i've listed just [INFO]Xplugin loaded etc. 
no [WARNING]s 
no [SEVERE]s

However, on reload the server does get this new line.
    [SEVERE] java.lang.UnsatisfiedLinkError: Native Library 
    C:\Users\J3lack\Desktop\MCServers\plugins\LWC\lib\native\Windows\x86\sqlitejdbc.dll 
    already loaded in another classloader

I believe this is just occuring because LWC also runs with sqlite but it can't be the source of my problem since i still get the previous errors without LWC installed.

Thank you for your help ^_^
