### ISSUE TITLE
/money internal error

### ISSUE THREAD

**Issue by Spiritwo** [iConomy/Core#173]
When typing the command /money on my server, it comes up as:

An internal error occurred while attempting to perform this command

No errors show in the console at this time.

**Comment by roastchicken** [comment]
when I use /money nothing happens =/

**Comment by Eonalias** [comment]
I've the same error when i type /money in game : "An internal error occurred while attempting to perform this command".
Also when i type "/money give someone amount". 
But it ok when i type "/money top"

I use Iconomy 7.0 and GroupManager. 
I already check the syntax of YAML config files for plugins.
When i've the error in gmae, my server log say :

2012-04-03 14:40:03 [SEVERE] Exception in thread "AWT-EventQueue-0" 
2012-04-03 14:40:03 [SEVERE] org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
2012-04-03 14:40:03 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
2012-04-03 14:40:03 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
2012-04-03 14:40:03 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
2012-04-03 14:40:03 [SEVERE]    at me.escapeNT.pail.GUIComponents.ServerConsolePanel$ConsoleCommandListener.actionPerformed(ServerConsolePanel.java:78)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JTextField.fireActionPerformed(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JTextField.postActionEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JTextField$NotifyAction.actionPerformed(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.SwingUtilities.notifyAction(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JComponent.processKeyBinding(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JComponent.processKeyBindings(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at javax.swing.JComponent.processKeyEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Component.processEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Container.processEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Component.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Container.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Component.dispatchEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Component.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Container.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Window.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.Component.dispatchEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue.access$000(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue$3.run(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue$3.run(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)
2012-04-03 14:40:03 [SEVERE]    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue$4.run(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue$4.run(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)
2012-04-03 14:40:03 [SEVERE]    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventQueue.dispatchEvent(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
2012-04-03 14:40:03 [SEVERE]    at java.awt.EventDispatchThread.run(Unknown Source)
2012-04-03 14:40:03 [SEVERE] Caused by: java.lang.NullPointerException
2012-04-03 14:40:03 [SEVERE]    at com.iCo6.util.Messaging.colorize(Messaging.java:128)
2012-04-03 14:40:03 [SEVERE]    at com.iCo6.util.Template.color(Template.java:93)
2012-04-03 14:40:03 [SEVERE]    at com.iCo6.handlers.Money.perform(Money.java:33)
2012-04-03 14:40:03 [SEVERE]    at com.iCo6.iConomy.onCommand(iConomy.java:417)
2012-04-03 14:40:03 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-04-03 14:40:03 [SEVERE]    ... 42 more

**Comment by Smidds** [comment]
Jesus I hope he knows about this...

Here's my log:
08.04 17:09:11 [Server] INFO    ... 14 more
08.04 17:09:11 [Server] INFO    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
08.04 17:09:11 [Server] INFO    at com.iCo6.iConomy.onCommand(iConomy.java:418)
08.04 17:09:11 [Server] INFO    at com.iCo6.handlers.Money.perform(Money.java:47)
08.04 17:09:11 [Server] INFO    at com.iCo6.system.Holdings.showBalance(Holdings.java:50)
08.04 17:09:11 [Server] INFO    at com.iCo6.system.Holdings.toString(Holdings.java:116)
08.04 17:09:11 [Server] INFO    at com.iCo6.util.Common.formatted(Common.java:84)
08.04 17:09:11 [Server] INFO    at java.lang.Long.valueOf(Long.java:540)
08.04 17:09:11 [Server] INFO    at java.lang.Long.parseLong(Long.java:444)
08.04 17:09:11 [Server] INFO    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
08.04 17:09:11 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "100000000000000000000000000"
08.04 17:09:11 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
08.04 17:09:11 [Server] INFO    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:169)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
08.04 17:09:11 [Server] INFO    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:103)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
08.04 17:09:11 [Server] INFO    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
08.04 17:09:11 [Server] INFO    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
08.04 17:09:11 [Server] INFO    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
08.04 17:09:11 [Server] INFO    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
08.04 17:09:11 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v6.0.9b
08.04 17:09:11 [Server] SEVERE null

I'm running the Latest CB (1.2.4)
and i've got 6.0.9b

Whoops... found out my money was set to some absurdly high number... set it to 300, problem solved!

**Comment by nijikokun** [comment]
Absurdly high numbers will do this, but the guy above you:

me.escapeNT.pail.GUIComponents.ServerConsolePanel$ConsoleCommandListener.actionPerformed(ServerConsolePanel.java:78)

pail is causing issues, spout / pail.

**Comment by Eonalias** [comment]
"pail is causing issues, spout / pail."

I've uninstalled pail and pail+. And i replaced it by BukkitGUI Projetc. But when i type command /money :

16:53:47 [SEVERE] null
16:53:48 org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
16:53:48    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
16:53:48    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
16:53:48    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
16:53:48    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
16:53:48    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
16:53:48    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
16:53:48    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
16:53:48    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
16:53:48    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
16:53:48    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
16:53:48    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:53:48    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
16:53:48    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
16:53:48 Caused by: java.lang.NullPointerException
16:53:48    at com.iCo6.util.Messaging.colorize(Messaging.java:128)
16:53:48    at com.iCo6.util.Template.color(Template.java:93)
16:53:48    at com.iCo6.handlers.Money.perform(Money.java:33)
16:53:48    at com.iCo6.iConomy.onCommand(iConomy.java:417)
16:53:48    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
16:53:48    ... 12 more

I use the iconomy 7.0 and work on "CraftBukkit version git-Bukkit-1.2.5-R1.0-b2149jnks".
PS : only /money top works :'(

**Comment by nijikokun** [comment]
colorizeeee

**Comment by Eonalias** [comment]
can you explain ?

I search other answer on forums but i havent found solution :(
You thing that be the plugin essential?

That is my plugin list : 
-Catacombs
-ChestRestock
-Citizens
-CreativeControl
-DeathTpPlus
-Dynmap
-EasyEcnhant
-Essentials
-EssentialsChat
-EssentialsGroupBridge
-EssentialsGroupManager
-EssentialsSpawn
-GlowstoneLanterns
-iConomy7
-LeTime
-Lockette
-Minequery
-MoneyDrop
-Multiverse-Core-2.4
-Multiverse-Portals-2.4
-Multiverse-SignPortals-2.4
-NoPortals
-PluginSpy
-PorteCoulissante
-SnoGro
-SnowBallNextDoor
-Spectate
-Turnstile
-Vault
-Whitelist
-WorldEdit
-WorldGuard

Thanks for your help

**Comment by roastchicken** [comment]
Um, I'm just another troubled user, I didn't make this plugin or know why this error is happening. Ask the author.
