### ISSUE TITLE
/money top No longer takes status into account

### ISSUE THREAD

**Issue by gabizou** [iConomy/Core#177]
So the status of a few admins are 0, presuming that means hidden.

When I attempt to change the status ingame with
/money status gabizou hidden

I get this:
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:620)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
        at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:117)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:60)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:85)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:625)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:509)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NumberFormatException: For input string: "hidden"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.valueOf(Integer.java:582)
        at com.iCo6.command.Parser$Argument.getIntegerValue(Parser.java:376)
        at com.iCo6.handlers.Status.perform(Status.java:68)
        at com.iCo6.iConomy.onCommand(iConomy.java:417)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 14 more

Also when using /money top, even accounts with status as 0 are showing up. 

Secondly, /money top ## doesn't show the number of accounts to show anymore as it did in iC5.

**Comment by nijikokun** [comment]
/money status 1|0

THOSE only.

**Comment by gabizou** [comment]
EDIT: I figured out, statuses are odd so /money status gabizou hidden doesn't work, BUT /money status gabizou 1 will hide my status from /money top.

Maybe a fix for /money status <player> <statusname> ?

**Comment by nijikokun** [comment]
I'll add a fix for it only accepting integers 1 && 0
