### ISSUE TITLE
/money error

### ISSUE THREAD

**Issue by hackal** [iConomy/Core#180]
this is output of console when i wrote /money

org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.iCo6.util.Common.formatted(Common.java:125)
        at com.iCo6.system.Holdings.toString(Holdings.java:116)
        at com.iCo6.system.Holdings.showBalance(Holdings.java:50)
        at com.iCo6.handlers.Money.perform(Money.java:47)
        at com.iCo6.iConomy.onCommand(iConomy.java:417)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 12 more

Bukkit version is CB 1.2.4-R1.0

plugins I use are: WorldGuarg, WorldEdit, LWC, iConomy, Essentials, ChatManager, PermissionsEx, EssentialsSpawn, EssentialsProtect, ModifyWorld, ChestShop, EssentialsChat, CreeperHeal. (Copied from server after /plugins)

**Comment by Smidds** [comment]
I seem to get this funky error too... no idea why

**Comment by vman411gamer** [comment]
Me too

**Comment by thibaultcha** [comment]
Same here...

**Comment by linkinkov** [comment]
same
