### ISSUE TITLE
MySQL autoReconnect=true

### ISSUE THREAD

**Issue by jascotty2** [iConomy/Core#19]
got a really long error message, but the key lines in it are:

```
2011-03-11 20:53:47 [INFO] [iConomy] Failed to grab player balance: java.lang.NullPointerException
2011-03-11 20:53:47 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.Connection was implicitly closed due to underlying exception/error:


** BEGIN NESTED EXCEPTION ** 

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException
MESSAGE: The last packet successfully received from the server was46326 seconds ago.The last packet sent successfully to the server was 46326 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

STACKTRACE:

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was46326 seconds ago.The last packet sent successfully to the server was 46326 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
```

......................
    at com.nijiko.coelho.iConomy.net.iDatabase.resultQuery(iDatabase.java:41)
    at com.nijiko.coelho.iConomy.system.Account.getBalance(Account.java:48)
    at com.nijiko.coelho.iConomy.system.Account.add(Account.java:119)
    at com.pi.coelho.CookieMonster.entity.cmRewardHandler.GivePlayerCoinReward(cmRewardHandler.java:33)
......................
    2011-03-11 20:53:47 [SEVERE] java.lang.NullPointerException
    2011-03-11 20:53:47 [SEVERE]    at com.nijiko.coelho.iConomy.system.Account.setBalance(Account.java:76)
    2011-03-11 20:53:47 [SEVERE]    at com.nijiko.coelho.iConomy.system.Account.add(Account.java:119)

**Comment by nijikokun** [comment]
Hopefully this is fixed with 4.4.7 where it disconnects to push the updates and starts a new connection.
