### ISSUE TITLE
Iconomy: all players lose their money after a warning.

### ISSUE THREAD

**Issue by Switch0r** [iConomy/Core#196]
This is the second time all our players and towns lose their money, first time the error was with HeroBounty now it is with votifier.
Players are beginning to hate the server now :p
What could be the cause of this problem?

2012-04-29 18:57:22 [INFO] [Votifier][VaultListener 1.1.1] mandariinimies99
2012-04-29 18:57:22 [INFO] mandariinimies99 voted on minestatus and recieved 30.0 dollar!
2012-04-29 18:57:22 [WARNING] Exception caught while sending the vote notification to a listener
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
    at java.util.LinkedList$ListItr.next(Unknown Source)
    at com.iCo6.IO.mini.Mini.read(Mini.java:148)
    at com.iCo6.IO.mini.Mini.update(Mini.java:360)
    at com.iCo6.system.Queried.setBalance(Queried.java:427)
    at com.iCo6.system.Holdings.setBalance(Holdings.java:26)
    at com.iCo6.system.Holdings.math(Holdings.java:103)
    at com.iCo6.system.Holdings.add(Holdings.java:58)
    at net.milkbowl.vault.economy.plugins.Economy_iConomy6.depositPlayer(Economy_iConomy6.java:144)
    at VaultListener.voteMade(VaultListener.java:178)
    at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:145)
2012-04-29 18:57:35 [INFO] [TownyChat] [Town Msg] Oceania: [TC] Mr. noahboa1999: why do i have 30.00
2012-04-29 18:57:42 [INFO] [TownyChat] [Town Msg] Oceania: [TC] Cheiftan pizzadanman: Wttff
2012-04-29 18:57:47 [INFO] [TownyChat]   Raw_c: i cant join
2012-04-29 18:57:48 [INFO] [TownyChat] [Town Msg] Oceania: [TC] Cheiftan pizzadanman: FUuck
2012-04-29 18:57:52 [INFO] [TownyChat] [Town Msg] Oceania: [TC] Cheiftan pizzadanman: Economy resett
2012-04-29 18:57:53 [INFO] [TownyChat] [Town Msg] Oceania: [TC] Cheiftan pizzadanman: oajtuoansfinaswftgaw
2012-04-29 18:57:57 [INFO] [TownyChat]   Raw_c: why?
2012-04-29 18:57:57 [INFO] [TownyChat]  [Mombasa|Oceania]  Mr. noahboa1999: switch why did you reset the economy?

**Comment by Switch0r** [comment]
Ok this was our first money loss and i thought it was HeroBounty first but then i think its iconomy.

2012-04-22 18:51:09 [SEVERE] null
org.bukkit.command.CommandException Unhandled exception executing command 'bounty' in plugin HeroBounty v1.8.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:92)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:622)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(Unknown Source)
    at java.util.LinkedHashMap$KeyIterator.next(Unknown Source)
    at com.iCo6.IO.mini.Mini.update(Mini.java:362)
    at com.iCo6.system.Queried.setBalance(Queried.java:427)
    at com.iCo6.system.Holdings.setBalance(Holdings.java:26)
    at com.iCo6.system.Holdings.math(Holdings.java:103)
    at com.iCo6.system.Holdings.add(Holdings.java:58)
    at net.milkbowl.vault.economy.plugins.Economy_iConomy6.depositPlayer(Economy_iConomy6.java:144)
    at com.herocraftonline.dthielke.herobounty.command.commands.CancelCommand.execute(Unknown Source)
    at com.herocraftonline.dthielke.herobounty.command.CommandHandler.dispatch(Unknown Source)
    at com.herocraftonline.dthielke.herobounty.HeroBounty.onCommand(Unknown Source)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 12 more

**Comment by stephenthoma** [comment]
This is also happening to me

**Comment by nijikokun** [comment]
`at net.milkbowl.vault.economy.plugins.Economy_iConomy6.depositPlayer(Economy_iConomy6.java:144)`

report this to vault.

**Comment by Sleaker** [comment]
@Nijikokun has nothing to do with Vault. Votifier runs all it's stuff in a seperate thread from what I know. 

Vault code:

```
public EconomyResponse depositPlayer(String playerName, double amount) {
    Holdings holdings = accounts.get(playerName).getHoldings();
    holdings.add(amount);
    return new EconomyResponse(amount, holdings.getBalance(), ResponseType.SUCCESS, null);
}
```

Obviously this isn't going to fire a ConcurrentModException unless iCo6 is non-thread safe (it errors on the holdings.add(amount))

**Comment by stephenthoma** [comment]
"This is not a Vault issue.  It's an issue with iCo6 not being thread safe, and Votifier attempting to use it in a thread."

**Comment by Switch0r** [comment]
Ok it happend again, can someone suggest me another iconomy plugin?

2012-05-06 10:20:29 [SEVERE] Exception in thread "Thread-9929" 
2012-05-06 10:20:29 [SEVERE] java.util.ConcurrentModificationException
2012-05-06 10:20:29 [SEVERE]    at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
2012-05-06 10:20:29 [SEVERE]    at java.util.LinkedList$ListItr.next(Unknown Source)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.IO.mini.Mini.read(Mini.java:148)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.IO.mini.Mini.update(Mini.java:360)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.system.Queried.setBalance(Queried.java:427)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.system.Holdings.setBalance(Holdings.java:26)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.system.Holdings.math(Holdings.java:103)
2012-05-06 10:20:29 [SEVERE]    at com.iCo6.system.Holdings.subtract(Holdings.java:65)
2012-05-06 10:20:29 [SEVERE]    at com.nijikokun.register.payment.methods.iCo6$iCoAccount.subtract(iCo6.java:122)
2012-05-06 10:20:29 [SEVERE]    at com.nijikokun.register.payment.methods.iCo6$iCoAccount.subtract(iCo6.java:177)
2012-05-06 10:20:29 [SEVERE]    at com.palmergames.bukkit.towny.object.TownyEconomyObject._pay(TownyEconomyObject.java:52)
2012-05-06 10:20:29 [SEVERE]    at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:102)
2012-05-06 10:20:29 [SEVERE]    at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:91)
2012-05-06 10:20:29 [SEVERE]    at com.palmergames.bukkit.towny.tasks.PlotClaim.residentClaim(PlotClaim.java:167)
2012-05-06 10:20:29 [SEVERE]    at com.palmergames.bukkit.towny.tasks.PlotClaim.run(PlotClaim.java:71)

**Comment by Sleaker** [comment]
@Switch0r - the issue only happens if you use Niji's flatfile db that he wrote himself.  It wasn't written to support a threaded environment, so it has issue when using plugins like Votifier which run in a seperate thread.  If you don't want to switch you can keep using it but simply switch over to using an SQL database for storing the data instead.
