### ISSUE TITLE
[SEVERE] Exception in thread "Thread-18" 

### ISSUE THREAD

**Issue by Switch0r** [iConomy/Core#202]
We get this on startup.

2012-05-05 10:10:26 [INFO] [Vault][Economy] iConomy 6 hooked.
2012-05-05 10:10:26 [INFO] [Register] Enabling Register v1.8
2012-05-05 10:10:26 [INFO] Unable to hook register
2012-05-05 10:10:26 [INFO] [Register] Payment method found (iConomy version: 6)
2012-05-05 10:10:26 [INFO] [boosCooldown] Enabling boosCooldown v2.6.6
2012-05-05 10:10:26 [INFO] [boosCooldown] version 2.6.6 by [boosik] is enabled!
2012-05-05 10:10:26 [SEVERE] Exception in thread "Thread-18" 
2012-05-05 10:10:26 [SEVERE] java.lang.NullPointerException
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.IO.mini.Arguments.decode(Arguments.java:38)
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.IO.mini.Arguments.getValue(Arguments.java:50)
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58)
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.system.Queried.purgeDatabase(Queried.java:535)
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.iConomy$2.run(iConomy.java:262)
2012-05-05 10:10:26 [SEVERE]    at com.iCo6.util.Thrun.run(Thrun.java:12)
2012-05-05 10:10:26 [INFO] [boosCooldown] found [Vault] searching for economy plugin.
2012-05-05 10:10:26 [INFO] [boosCooldown] found [Vault] searching for permissions plugin.
2012-05-05 10:10:26 [INFO] [boosCooldown] found [iConomy 6] plugin, enabling prices support.
2012-05-05 10:10:26 [INFO] [boosCooldown] found [GroupManager] plugin, enabling permissions support.
2012-05-05 10:10:26 [INFO] [pvparena] Enabling pvparena v0.7.20.2
2012-05-05 10:10:27 [INFO] [PVP Arena] Checking for updates...
2012-05-05 10:10:27 [INFO] [PVP Arena] Plugin tracking enabled. Set stats: false inside the main config to disable.
2012-05-05 10:10:27 [INFO] [PVP Arena] Spout not found, you are missing some features ;)
2012-05-05 10:10:27 [INFO] [PVP Arena] enabled (version pvparena v0.7.20.2)
2012-05-05 10:10:27 [INFO] [OpenInv] Enabling OpenInv v1.8.4
2012-05-05 10:10:27 [INFO] [OpenInv] version 1.8.4 enabled!
2012-05-05 10:10:27 [INFO] [SmithChest] Enabling SmithChest v1.4

**Comment by Switch0r** [comment]
All our players are losing their money for the 5th time now.

Heres the link https://github.com/iConomy/Core/issues/196

We changed to boseconomy for now
