### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Haarolean** [iConomy/Core#210]
[SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mone
y' in plugin iConomy v7.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:16
6)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:4
73)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:821)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
```

:103)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
:169)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:7
8)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
        at com.iCo6.util.Messaging.colorize(Messaging.java:128)
        at com.iCo6.util.Template.color(Template.java:93)
        at com.iCo6.handlers.Money.perform(Money.java:33)
        at com.iCo6.iConomy.onCommand(iConomy.java:417)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 14 more

**Comment by kylekz** [comment]
I've got this error as well, and a fix is needed soon, no other economy plugin suits. :/
