### ISSUE TITLE
iConomy presents Unhandled exception executing command 'money' in plugin iConomy v7.0

### ISSUE THREAD

**Issue by jcrosseto** [iConomy/Core#275]
The iConomy plugin, which is using MySQL, presents this error when I use / money, can anyone help me?

2014-05-19 21:09:20 [INFO] Kaspar87 issued server command: /money
2014-05-19 21:09:21 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
    at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:971)
    at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:889)
    at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:846)
    at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
    at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:115)
    at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at com.iCo6.util.Messaging.colorize(Messaging.java:128)
    at com.iCo6.util.Template.color(Template.java:93)
    at com.iCo6.handlers.Money.perform(Money.java:33)
    at com.iCo6.iConomy.onCommand(iConomy.java:417)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

**Comment by mattataki** [comment]
+1
