### ISSUE TITLE
Severe Error... :)

### ISSUE THREAD

**Issue by chuckzee** [iConomy/Core#46]
Hey, I'm trying to run Iconomy on my server... but I get the same error message every time I start up the server. I'm also running the MCMMO plugin, the nether plug in, monster tamer, phoenix permissions, simple barter, and vstopfire. Would any of these conflict with it, possibly? 

[INFO] [iConomy] Default setup file written: iConomy.yml
2011-03-31 20:38:07 [INFO] [iConomy] Default setup file written: Messages.yml
2011-03-31 20:38:07 [INFO] [iConomy] Logging is currently disabled.
2011-03-31 20:38:09 [SEVERE] class com.nijiko.coelho.iConomy.entity.Players overrides final method onPlayerJoin.(Lorg/bukkit/event/player/PlayerEvent;)V loading iConomy v4.63 (Is it up to date?)
java.lang.VerifyError: class com.nijiko.coelho.iConomy.entity.Players overrides final method onPlayerJoin.(Lorg/bukkit/event/player/PlayerEvent;)V
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:142)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:32)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:169)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:511)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:216)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:93)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:71)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:204)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:191)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:131)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:246)

If I run it without, my server runs fine:

21:14:52 [INFO] Starting minecraft server version Beta 1.3
21:14:52 [INFO] Loading properties
21:14:52 [INFO] Starting Minecraft server on *:25565
21:14:52 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-605-
g376d7e8-b602jnks (MC: 1.3)
21:14:52 [INFO] Preparing level "Hodsonia"
21:14:52 [INFO] Preparing start region
21:14:53 [INFO] Preparing spawn area: 4%
21:14:54 [INFO] Preparing spawn area: 36%
21:14:55 [INFO] Preparing spawn area: 65%
21:14:57 [INFO] Invalid config file found and converted to proper name/format.
21:14:57 [INFO] [Permissions](Phoenix) was Initialized.
21:14:57 [INFO] [mcMMO] Permissions enabled.
21:14:57 [INFO] mcMMO version 0.9.14 is enabled!
21:14:57 [INFO] [MonsterTamer]: version [1.23](Companions) loaded
21:14:57 [INFO] Nether v1.1 enabled
21:14:57 [INFO] [Permissions] version [2.5.5](Phoenix)  loaded
21:14:58 [INFO] Simple Barter version 1.1 is enabled!
21:14:58 [INFO] vStopFire version 1.2 is enabled!
21:14:58 [INFO] Done (0.567s)! For help, type "help" or "?"

```
at net.minecraft.server.ThreadServerApplication.run(SourceFile:366)
```

**Comment by nijikokun** [comment]
Using 556 on 600+, learn to correctly use version!
