### ISSUE TITLE
[SEVERE] tried to access class com.nijiko.coelho.iConomy.iConomy$Listener from class com.nijiko.coelho.iConomy.iConomy loading iConomy

### ISSUE THREAD

**Issue by ghost** [iConomy/Core#50]
Craftbukkit Version: 617
iConomy version: 4.6.5
Current Issue / Error: 

18:25:15 [SEVERE] tried to access class com.nijiko.coelho.iConomy.iConomy$Listener from class com.nijiko.coelho.iConomy.iConomy loading iConomy v4.65 (Is it up to date?)
java.lang.IllegalAccessError: tried to access class com.nijiko.coelho.iConomy.iConomy$Listener from class com.nijiko.coelho.iConomy.iConomy
at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:174)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:118)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:514)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:216)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:94)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:72)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:215)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:202)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:142)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:257)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:375)

Console Output w/ Full Error See above! ^^

What you were doing? Starting the server.

Were you upgrading? Yes.

Is this a reoccuring issue? Yes, everytime the server starts.

**Comment by nijikokun** [comment]
Read the FAQ, this is caused by plugins incorrectly attempting to use our classes.
