### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mace1313** [iConomy/Core#52]
Hey, I'm trying to run Iconomy on my server... but I get this error : 

  Logging is currently disabled.
12:37:46 [INFO] [iConomy] Could not create connection: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
12:37:46 [SEVERE] null loading iConomy v4.65 (Is it up to date?)
java.lang.NullPointerException
        at com.nijiko.coelho.iConomy.iConomy.update(iConomy.java:313)
        at com.nijiko.coelho.iConomy.iConomy.onEnable(iConomy.java:145)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:127)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:578)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:216)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:115)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:93)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:215)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:202)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:142)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:257)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:375)

Database:
        # Can be MySQL, or H2SQL
        Type: MySQL
        # Name of the database
        Name: localhost
        # Table name
        Table: iConomy
        # Mysql Details
        MySQL:
            # MySQL Login Username
            Username: 'root'
            # MySQL Login Password
            Password: '********'
            # MySQL Connection Hostname (IP)
            Hostname: '88.190.18.209'
            # MySQL Connection Port Number
            Port: 3306

**Comment by nijikokun** [comment]
Invalid database settings most likely
