### ISSUE TITLE
interst is not working

### ISSUE THREAD

**Issue by antwan6969** [iConomy/Core#83]
i try to make interest work on my server and its not working here is the error:
17:04:02 [SEVERE] Could not load 'plugins\iConomy.jar' in folder 'plugins':
mapping values are not allowed here
 in "<reader>", line 82, column 19:
                Cutoff: 0.0                            ...
                      ^

```
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:74
```

5)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.ja
va:307)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:18
3)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(Par
serImpl.java:564)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:228)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:230)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:230)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:12
2)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)

```
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
```

tructor.java:124)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
        at org.bukkit.util.config.Configuration.load(Configuration.java:73)
        at org.bukkit.plugin.java.JavaPlugin.initialize(JavaPlugin.java:158)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:166)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:191)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:115)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:100)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:218)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:205)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:145)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:260)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:394)
17:04:03 [INFO] DataSourcePool [iConomyChestShop] autoCommit[false] transIsolati
on[SERIALIZABLE] min[2] max[20]
17:04:03 [INFO] SubClassFactory parent ClassLoader [org.bukkit.plugin.java.Plugi
nClassLoader]
17:04:03 [INFO] Entities enhanced[0] subclassed[1]

**Comment by nijikokun** [comment]
Seems like your yaml has a snakey issue.
