### ISSUE TITLE
/money stats

### ISSUE THREAD

**Issue by Hpiz** [iConomy/Core#88]
19:15:04 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v5.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:85)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:278)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:699)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:664)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:658)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:32)
    at net.minecraft.server.NetworkManager.a(NetworkManager.java:196)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:75)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:100)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:372)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:287)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:394)
```

Caused by: java.lang.NullPointerException
        at com.iConomy.util.Messaging.argument(Messaging.java:42)
        at com.iConomy.util.Template.parse(Template.java:119)
        at com.iConomy.entity.Players.onPlayerCommand(Players.java:1648)
        at com.iConomy.iConomy.onCommand(iConomy.java:218)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
        ... 12 more

**Comment by jigsawspain** [comment]
i second this

**Comment by nijikokun** [comment]
Fixed in 6
